// This file is @generated by prost-build.
/// 交易输出点 COutPoint
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutPoint {
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub n: u32,
}
/// 交易输入 CTxIn
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TxIn {
    #[prost(message, optional, tag = "1")]
    pub preout: ::core::option::Option<OutPoint>,
    #[prost(bytes = "vec", tag = "2")]
    pub script_sig: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub sequence: u32,
}
/// 交易输出 CTxOut
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TxOut {
    #[prost(uint64, tag = "1")]
    pub value: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub script_pubkey: ::prost::alloc::vec::Vec<u8>,
}
/// 隔离见证 CTxWitness
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Witness {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub stack: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// 主交易结构 CTransaction
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(message, repeated, tag = "2")]
    pub vin: ::prost::alloc::vec::Vec<TxIn>,
    #[prost(message, repeated, tag = "3")]
    pub vout: ::prost::alloc::vec::Vec<TxOut>,
    #[prost(message, repeated, tag = "4")]
    pub witnesses: ::prost::alloc::vec::Vec<Witness>,
    #[prost(uint32, tag = "5")]
    pub lock_time: u32,
}
/// 区块头 CBlockHeader
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockHeader {
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub prev_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub merkle_root_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub n_time: u32,
    #[prost(uint32, tag = "5")]
    pub n_bits: u32,
    #[prost(uint32, tag = "6")]
    pub nonce: u32,
}
/// 区块 CBlock
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<BlockHeader>,
    #[prost(message, repeated, tag = "2")]
    pub txs: ::prost::alloc::vec::Vec<Transaction>,
}
